// keymap.h

#ifndef _KEYMAP_h
#define _KEYMAP_h

#if defined(ARDUINO) && ARDUINO >= 100
	#include "arduino.h"
#else
	#include "WProgram.h"
#endif

#include "keylayouts.h"

#define KEY_BSPC KEY_BACKSPACE

#define KEY_PSCR	KEY_PRINTSCREEN
#define KEY_DEL		KEY_DELETE
#define KEY_INS		KEY_INSERT
#define KEY_SPC		KEY_SPACE
#define KEY_RETURN	KEY_ENTER
#define KEY_LCTL	MODIFIERKEY_LEFT_CTRL
#define KEY_LSFT	MODIFIERKEY_LEFT_SHIFT
#define KEY_LALT	MODIFIERKEY_LEFT_ALT
#define KEY_LGUI	MODIFIERKEY_LEFT_GUI
#define KEY_RCTL	MODIFIERKEY_RIGHT_CTRL
#define KEY_RSFT	MODIFIERKEY_RIGHT_SHIFT
#define KEY_RALT	MODIFIERKEY_RIGHT_ALT
#define KEY_RGUI	MODIFIERKEY_RIGHT_GUI
#define KEY_PGDN	KEY_PAGE_DOWN
#define KEY_PGUP	KEY_PAGE_UP
#define KEY_VOLD	KEY_MEDIA_VOLUME_DEC
#define KEY_VOLU	KEY_MEDIA_VOLUME_INC
#define KEY_MUTE	KEY_MEDIA_MUTE
#define KEY_MPLY	KEY_MEDIA_PLAY_PAUSE
#define KEY_MPRV	KEY_MEDIA_PREV_TRACK
#define KEY_MNXT	KEY_MEDIA_NEXT_TRACK

#define KEY_PMNS	KEYPAD_MINUS
#define KEY_PSLS	KEYPAD_SLASH
#define KEY_PPLS	KEYPAD_PLUS
#define KEY_PDOT	KEYPAD_PERIOD
#define KEY_PAST	KEYPAD_ASTERIX
#define KEY_P0		KEYPAD_0
#define KEY_P1		KEYPAD_1
#define KEY_P2		KEYPAD_2
#define KEY_P3		KEYPAD_3
#define KEY_P4		KEYPAD_4
#define KEY_P5		KEYPAD_5
#define KEY_P6		KEYPAD_6
#define KEY_P7		KEYPAD_7
#define KEY_P8		KEYPAD_8
#define KEY_P9		KEYPAD_9

#define KEY_SCLN KEY_SEMICOLON
#define KEY_QUOT KEY_QUOTE
#define KEY_LBRC KEY_LEFT_BRACE
#define KEY_RBRC KEY_RIGHT_BRACE
#define KEY_COMM KEY_COMMA
#define KEY_DOT KEY_PERIOD
#define KEY_UNDS KEY_MINUS
#define KEY_EQL KEY_EQUAL
#define KEY_BSLASH KEY_BACKSLASH

#endif

